Generic amd64
balena-os/balena-generic pull request #122
Opened 2022-08-02 01:00 UTC by jakogut

I tested this with the unmanaged OS suite, ~~but we still need to test HUP~~ and manually tested HUP.

~~Additionally, I'm open to input on the full name for the DT.~~ We've settled on `Generic x86_64 (GPT)`

Relevant thread: https://jel.ly.fish/thread-560c1829-a97f-4d1b-8cc6-6320fb1d76b4

2022-08-02 10:31 UTC, alexgg commented
@jakogut let's take the name question to the product call, and also whether it should have an `amd` or `intel` logo

2022-08-02 10:32 UTC, alexgg reviewed
Left a couple of comments.

2022-08-02 10:32 UTC, alexgg commented on layers/meta-balena-generic/recipes-support/resin-init/resin-init-flasher.bbappend
> +INTERNAL_DEVICE_KERNEL = "sda vda nvme0n1"
Any reason to swap sda vs nvme compared with the -ext? If there is both nvme and sda, wouldn't it make more sense to install the OS into nvme?

2022-08-02 17:08 UTC, jakogut commented
> @jakogut let's take the name question to the product call, and also whether it should have an `amd` or `intel` logo

@alexgg I would actually prefer we not acknowledge any specific company in the logo (or maybe both?), given the fact that amd64/Intel 64/x86_64 is derived from technical contributions from _both_ companies, who cross license their patents to each other. I don't know if there's a company agnostic logo available for x86_64.

I do still like generic-amd64 for the slug, as it's faster and easier to type than x86_64, and is consistent with Balena and Docker in the naming of this architecture.

Product call item created. :)

2022-08-04 14:47 UTC, jakogut commented on layers/meta-balena-generic/recipes-support/resin-init/resin-init-flasher.bbappend
> +INTERNAL_DEVICE_KERNEL = "sda vda nvme0n1"
I'll go ahead and revert this to the existing value, with the addition of `vda` for virtio disks. We discussed in the call that to avoid confusion, we should minimize differences between these two device types, and `generic-amd64` should generally be a superset of `genericx86-64-ext`.

2022-08-07 21:58 UTC, klutchell approved these changes
lgtm

2022-08-07 22:09 UTC, klutchell commented
@jakogut I've enabled the `generic-amd64` job on PRs for this repo, and we should get leviathan results as well. We can expect HUP to fail since no releases exist, but the other suites should pass.

2022-08-07 22:33 UTC, klutchell requested changes
```
[000000003][ERROR]"generic-amd64" is not a supported machine.
```
You need to rename the old machine config:
[`layers/meta-balena-generic/conf/machine/genericx86-64-ext.conf`](https://github.com/balena-os/balena-generic/blob/master/layers/meta-balena-generic/conf/machine/genericx86-64-ext.conf)

2022-08-08 23:20 UTC, jakogut commented
> You need to rename the old machine config:

@klutchell I'm a little confused, it should be renamed. I started this PR by reverting the rename from `generic-amd64` to `genericx86-64-ext`.

2022-08-08 23:20 UTC, jakogut commented
@resin-jenkins retest this please

2022-08-09 12:05 UTC, klutchell commented
HUP failed as expected, but I've never seen this cloud failure before. Perhaps because the device does not exist in the dashboard in order to create the app? Unmanaged tests passed though which is good.
```
jenkins-leviathan-v2-template-3664-client-1  | [2022-08-09T00:59:21.197Z][worker-cloud] Getting application config.json...
jenkins-leviathan-v2-template-3664-client-1  | [2022-08-09T00:59:22.151Z][worker-cloud] # Subtest: Managed BalenaOS release suite
jenkins-leviathan-v2-template-3664-client-1  | [2022-08-09T00:59:22.151Z][worker-cloud]     not ok 1 - Application not found: testbot/off5k12z
```
[consoleText4.txt](https://github.com/balena-os/balena-generic/files/9290173/consoleText4.txt)

2022-08-09 12:07 UTC, klutchell approved these changes

2022-08-09 12:08 UTC, klutchell commented
I agree with your earlier comments that this PR should not be failing, and is currently blocking other PRs.
https://github.com/balena-os/balena-generic/pull/113

2022-08-11 00:13 UTC, merged